### PR TITLE
Update index.html with another lad

### PR DESCRIPTION
**Pull request by Melinysh**
You know what to do.

### CODE REVIEW

**Review by JamesHageman — CHANGES_REQUESTED** [review]
Tests?

**Review by JamesHageman — CHANGES_REQUESTED** [review]
Screenshots?

**Comment by ethan-hardy** [comment]
:shipit:

**Comment by JamesHageman** [comment]
Can you at least add some 🎩 steps?

**Comment by Melinysh** [comment]
- [x] it is safe to rollback this change
- [x] I have checked for XSS and secuirity issues
- [x] I have notified the documentation team of any relevant front end changes 
- [x] I have added any relevant changes to the changelog
- [x] I have notified #datastores of any schema changes

**Review by JamesHageman — APPROVED** [review]
Rebase and 🚢

**Comment by georgeutsin** [comment]
Don't forget to squash and merge

**Comment by daniel5151** [comment]
sorry about the merge conflict :(

**Review by Melinysh — COMMENTED** [review]
Godamnn @daniel5151. Fixed conflict. Pls merge @JamesHageman.

**Comment by JamesHageman** [comment]
@Melinysh pls squash

**Pull request merged**
